kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-nginx-default
  namespace: homework
data:
  default.conf: |
    server {
        listen 8000;
        server_name localhost;
        location / {
            root   /homework;
            index  index.html index.htm;
        }
    }